import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useState, useEffect, use } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [channels, setChannels] = useState([]);

  useEffect(() => {
    const fetchChannels = async () => {
      const { data } = await axios.get("/api/channels");
      setChannels(data);
    };
    fetchChannels();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {channels.map((channel) => (
          <div key={channel.id}>
            <h1>{channel.name}</h1>
            <h3>{channel.created}</h3>
          </div>
        ))}
      </main>
    </>
  );
}
