import Head from "next/head";
import axios from "axios";
import { useState, useEffect } from "react";
import { AiFillDelete, AiFillEdit } from "react-icons/ai";
import Messages from "components/Messages/Messages";
import NewChannelForm from "components/NewChannelForm/NewChannelForm";
import EditForm from "components/EditForm/EditForm";
import UpdateButtons from "components/UpdateButtons/UpdateButtons";

export default function Home() {
  const [channels, setChannels] = useState([]);
  const [editMode, setEditMode] = useState(false);
  const [updatedData, setUpdatedData] = useState({});
  const [selectedChannelId, setSelectedChannelId] = useState(null);
  const [currentChannelName, setCurrentChannelName] = useState("");
  const [messageId, setMessageId] = useState(1);
  const [newChannelForm, setNewChannelForm] = useState(false);
  const [newChannelName, setNewChannelName] = useState("");

  const handleEdit = (id) => {
    setSelectedChannelId(id);
    setCurrentChannelName(channels.find((channel) => channel.id === id).name);
  };

  const deleteChannel = async (id) => {
    try {
      await axios.delete(`/api/channels/${id}`);
      setChannels(channels.filter((channel) => channel.id !== id));
    } catch (error) {
      console.log(error.message);
    }
  };

  const updateChannel = async (id, updatedData) => {
    if (Object.keys(updatedData).length > 0) {
      await axios.put(`/api/channels/${id}`, updatedData);
      setChannels(
        channels.map((channel) =>
          channel.id === id ? { ...channel, ...updatedData } : channel
        )
      );
      setUpdatedData({});
    } else {
      setEditMode(false);
    }
  };

  const createNewChannel = async () => {
    try {
      const { data } = await axios.post("/api/channels", {
        name: newChannelName,
      });
      setChannels([...channels, data]);
      setNewChannelName("");
    } catch (error) {
      console.log(error.message);
    }
  };

  useEffect(() => {
    const fetchChannels = async () => {
      const { data } = await axios.get("/api/channels");
      setChannels(data);
    };
    fetchChannels();
  });

  return (
    <>
      <Head>
        <title>Discord 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <main className="main-cont">
          <button
            className="bg-[#7289da] text-white px-2 py-1 rounded-lg my-4"
            onClick={() => {
              setNewChannelForm(!newChannelForm);
              createNewChannel();
            }}
          >
            New channel +
          </button>
          {newChannelForm && (
            <NewChannelForm
              handleValue={newChannelName}
              handleChange={(e) => {
                setNewChannelName(e.target.value);
              }}
              handleClick={() => {
                setNewChannelForm(!newChannelForm);
              }}
            />
          )}
          {channels.map((channel) => (
            <div
              key={channel.id}
              className="flex flex-row px-2 py-4 rounded-lg gap-8"
            >
              <h1 className="text-md text-[#f5f5f5]"># {channel.name}</h1>
              {editMode && selectedChannelId === channel.id ? (
                <EditForm
                  handleSubmit={(e) => {
                    e.preventDefault();
                    updateChannel(channel.id, updatedData);
                    setEditMode(false);
                  }}
                  defaultValue={currentChannelName}
                  handleChange={(e) => {
                    setCurrentChannelName(e.target.value);
                    setUpdatedData({ ...updatedData, name: e.target.value });
                  }}
                  handleClick={() => {
                    setEditMode(false);
                  }}
                />
              ) : (
                <>
                  <UpdateButtons
                    handleEditClick={() => {
                      setEditMode(true);
                      handleEdit(channel.id);
                    }}
                    handleDeleteClick={() => {
                      deleteChannel(channel.id);
                    }}
                  />
                </>
              )}
            </div>
          ))}
        </main>
        <Messages messageId={messageId} />
      </div>
    </>
  );
}
